/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Include_constants.h"



const IncludeConstants g_Include_constants;

IncludeConstants::IncludeConstants() {
}



