/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Include_CONSTANTS_H
#define Include_CONSTANTS_H

#include "Include_types.h"



class IncludeConstants {
 public:
  IncludeConstants();

};

extern const IncludeConstants g_Include_constants;



#endif
